In [8]:
import pandas as pd
import numpy as np
data = {'sate':['0hio','0hio','0hio','Nevada','Nevada'],
        'year':[2000,2001,2002,2001,2002],
       'pop':[1.5,1.7,3.6,2.1,2.9]}
frame = pd.DataFrame(data)
frame

pop    sate  year
0  1.5    0hio  2000
1  1.7    0hio  2001
2  3.6    0hio  2002
3  2.1  Nevada  2001
4  2.9  Nevada  2002

In [10]:
pd.DataFrame(data,columns=['year','state','pop'])

year state  pop
0  2000   NaN  1.5
1  2001   NaN  1.7
2  2002   NaN  3.6
3  2001   NaN  2.1
4  2002   NaN  2.9

In [13]:
frame2 = pd.DataFrame(data,columns=['year','state','pop','debt'],
                     index=['one','two','three','four','five'])
frame2

year state  pop debt
one    2000   NaN  1.5  NaN
two    2001   NaN  1.7  NaN
three  2002   NaN  3.6  NaN
four   2001   NaN  2.1  NaN
five   2002   NaN  2.9  NaN

In [14]:
frame.columns

Index([u'pop', u'sate', u'year'], dtype='object')

In [16]:
frame2['state']

one      NaN
two      NaN
three    NaN
four     NaN
five     NaN
Name: state, dtype: object

In [17]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [18]:
frame2.ix['three']

year     2002
state     NaN
pop       3.6
debt      NaN
Name: three, dtype: object

In [20]:
frame2['debt'] = 16.5
frame2

year state  pop  debt
one    2000   NaN  1.5  16.5
two    2001   NaN  1.7  16.5
three  2002   NaN  3.6  16.5
four   2001   NaN  2.1  16.5
five   2002   NaN  2.9  16.5

In [21]:
frame2['debt'] = np.arange(5.)
frame2

year state  pop  debt
one    2000   NaN  1.5   0.0
two    2001   NaN  1.7   1.0
three  2002   NaN  3.6   2.0
four   2001   NaN  2.1   3.0
five   2002   NaN  2.9   4.0

In [23]:
val = pd.Series([-1.2,-1.5,-1.7],index=['two','four','five'])
frame2['debt'] = val
frame2

year state  pop  debt
one    2000   NaN  1.5   NaN
two    2001   NaN  1.7  -1.2
three  2002   NaN  3.6   NaN
four   2001   NaN  2.1  -1.5
five   2002   NaN  2.9  -1.7

In [24]:
frame2['eastern'] = frame2.state =='0hio'
frame2

year state  pop  debt eastern
one    2000   NaN  1.5   NaN   False
two    2001   NaN  1.7  -1.2   False
three  2002   NaN  3.6   NaN   False
four   2001   NaN  2.1  -1.5   False
five   2002   NaN  2.9  -1.7   False

In [27]:
del frame2['eastern']
frame2.columns

Index([u'year', u'state', u'pop', u'debt'], dtype='object')

In [33]:
pop = {'Nevada':{2001:2.4,2002:2.9},
       '0hio':{200:1.5,2001:1.7,2002:3.6}}
frame3 = pd.DataFrame(pop)
frame3

0hio  Nevada
200    1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [34]:
frame3.T

200   2001  2002
0hio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [36]:
pd.DataFrame(pop,index=[2201,2002,2003])

0hio  Nevada
2201   NaN     NaN
2002   3.6     2.9
2003   NaN     NaN

In [37]:
pdata = {'0hio':frame3['0hio'][:-1],
        'Nevada':frame3['Nevada'][:2]}
pd.DataFrame(pdata)

0hio  Nevada
200    1.5     NaN
2001   1.7     2.4

In [39]:
frame3.index.name = 'year';frame3.columns.name = 'state'
frame3

state  0hio  Nevada
year               
200     1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [40]:
frame3.values

array([[ 1.5,  nan],
       [ 1.7,  2.4],
       [ 3.6,  2.9]])

In [41]:
frame2.values

array([[2000L, nan, 1.5, nan],
       [2001L, nan, 1.7, -1.2],
       [2002L, nan, 3.6, nan],
       [2001L, nan, 2.1, -1.5],
       [2002L, nan, 2.9, -1.7]], dtype=object)

In [42]:
obj = pd.Series(range(3),index=['a','b','c'])
index = obj.index
index

Index([u'a', u'b', u'c'], dtype='object')

In [43]:
obj = pd.Series(range(3),index=['a','b','c'])
index = obj.index
index

Index([u'a', u'b', u'c'], dtype='object')

In [44]:
frame3

state  0hio  Nevada
year               
200     1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [45]:
'0hio' in frame3.columns

True

In [46]:
2003 in frame3.index

False

In [49]:
obj = pd.Series([4.5,7.2,-5.3,3.6],index = ['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [50]:
obj2 = obj.reindex(['a','b','c','d','2'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
2    NaN
dtype: float64

In [51]:
obj.reindex(['a','b','c','d','e'],fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [54]:
obj3 = pd.Series(['bule','purple','yellow'],index=[0,2,4])
obj3.reindex(range(6),method='ffill')

0      bule
1      bule
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [56]:
frame = pd.DataFrame(np.arange(9).reshape((3,3,)),index=['a','c','d'],
                 columns = ['0hio','Texas','California'])
frame

0hio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [57]:
frame2 =frame.reindex(['a','b','c','d'])
frame2

0hio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [60]:
states = ['Texas','Utah','California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [62]:
frame.reindex(index=['a','b','c','d'],method='ffill',
             columns=states)

Texas  Utah  California
a      1   NaN           2
b      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [63]:
frame.ix[['a','b','c','d'],states]

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [67]:
obj = pd.Series(np.arange(5.),index=['a','b','c','d','e'])
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [69]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [72]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                 index = ['0hio','Colorado','Utah','New York'],
                 columns = ['one','two','three','four'])
data.drop(['Colorado','0hio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [74]:
data.drop('two',axis=1)

one  three  four
0hio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [75]:
data.drop(['two','four'],axis=1)

one  three
0hio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [77]:
obj = pd.Series(np.arange(4.),index=['a','b','c','d'])
obj['b']

1.0

In [79]:
obj[1]

1.0

In [80]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [81]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [82]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [83]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [84]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [86]:
obj['b':'c']=5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [88]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                 index=['0hio','Colorado','Utah','New York'],
                 columns=['one','two','three','four'])
data

one  two  three  four
0hio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [89]:
data['two']

0hio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [90]:
data[['three','one']]

three  one
0hio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [91]:
data[:2]

one  two  three  four
0hio        0    1      2     3
Colorado    4    5      6     7

In [92]:
data[['three','one']]

three  one
0hio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [93]:
data[:2]

one  two  three  four
0hio        0    1      2     3
Colorado    4    5      6     7

In [95]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [96]:
data <5

one    two  three   four
0hio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [98]:
data[data < 5] =0
data

one  two  three  four
0hio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [99]:
data.ix['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [100]:
data.ix[['Colorado','Utah'],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [101]:
data.ix[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [102]:
data.ix[:'Utah','two']

0hio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [103]:
data.ix[data.three > 5,:3]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [105]:
s1 = pd.Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [106]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

s1 + s2

In [111]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)),columns=list('bcd'),
                index=['0hio','Texas','Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),
                  index=['Utah','0hio','Texas','Oregon'])
df1

b    c    d
0hio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [113]:
df2

b     d     e
Utah    0.0   1.0   2.0
0hio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [114]:
df1+df2

b   c     d   e
0hio      3.0 NaN   6.0 NaN
Colorado  NaN NaN   NaN NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [116]:
df1.add(df2,fill_value=0)

b    c     d     e
0hio      3.0  1.0   6.0   5.0
Colorado  6.0  7.0   8.0   NaN
Oregon    9.0  NaN  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  NaN   1.0   2.0

In [117]:
df1.reindex(columns=df2.columns,fill_value=0)

b    d  e
0hio      0.0  2.0  0
Texas     3.0  5.0  0
Colorado  6.0  8.0  0

In [123]:
arr = np.arange(12.).reshape((3,4))
arr

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [122]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [125]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),
                 index=['Utah','0hio','Texas','Oregon'])
series = frame.ix[0]
frame

b     d     e
Utah    0.0   1.0   2.0
0hio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [126]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [127]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
0hio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [129]:
series2 = pd.Series(range(3),index=['b','e','f'])
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
0hio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [130]:
series3 = frame['d']
frame

b     d     e
Utah    0.0   1.0   2.0
0hio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [131]:
series3

Utah       1.0
0hio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [132]:
frame.sub(series3,axis=0)

b    d    e
Utah   -1.0  0.0  1.0
0hio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [134]:
frame = pd.DataFrame(np.random.randn(4,3),columns=list('bde'),
                 index=['Utah','0hio','Texas','Oregon'])
frame

b         d         e
Utah    0.767322 -0.088215  0.105160
0hio   -0.245968 -0.120658  1.436217
Texas   0.417723 -0.593803  0.458069
Oregon -0.027647 -2.249438  0.326776

In [135]:
np.abs(frame)

b         d         e
Utah    0.767322  0.088215  0.105160
0hio    0.245968  0.120658  1.436217
Texas   0.417723  0.593803  0.458069
Oregon  0.027647  2.249438  0.326776

In [137]:
f = lambda x:x.max() - x.min()
frame.apply(f)

b    1.013290
d    2.161223
e    1.331057
dtype: float64

In [138]:
frame.apply(f,axis=1)

Utah      0.855537
0hio      1.682185
Texas     1.051872
Oregon    2.576215
dtype: float64

In [140]:
def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])
frame.apply(f)

b         d         e
min -0.245968 -2.249438  0.105160
max  0.767322 -0.088215  1.436217

In [141]:
format = lambda x:'%.2f' % x
frame.applymap(format)

b      d     e
Utah     0.77  -0.09  0.11
0hio    -0.25  -0.12  1.44
Texas    0.42  -0.59  0.46
Oregon  -0.03  -2.25  0.33

In [142]:
frame['e'].map(format)

Utah      0.11
0hio      1.44
Texas     0.46
Oregon    0.33
Name: e, dtype: object

In [144]:
obj = pd.Series(range(4),index=['d','a','b','c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [146]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),index=['three','one'],
                 columns=['d','a','b','c'])
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [147]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [148]:
frame.sort_index(axis=1,ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [155]:
#import kernelapp as app
obj = pd.Series([4,7,-3,2])
obj.order()
#app.sort_values(obj)这是针对python3的

c:\python27\lib\site-packages\ipykernel\__main__.py:3: FutureWarning: order is deprecated, use sort_values(...)
  app.launch_new_instance()


2   -3
3    2
0    4
1    7
dtype: int64

In [158]:
obj = pd.Series([4,np.nan,7,np.nan,-3,2])
obj.order()

c:\python27\lib\site-packages\ipykernel\__main__.py:2: FutureWarning: order is deprecated, use sort_values(...)
  from ipykernel import kernelapp as app


4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [160]:
frame = pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [161]:
frame.sort_index(by='b')

c:\python27\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)
  if __name__ == '__main__':


a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [162]:
frame.sort_index(by=['a','b'])

c:\python27\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)
  if __name__ == '__main__':


a  b
2  0 -3
0  0  4
3  1  2
1  1  7

In [164]:
obj= pd.Series([7,-5,7,4,2,0,4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [165]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [166]:
obj.rank(ascending=False,method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [168]:
frame = pd.DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],
                  'c':[-2,5,8,-2.5]})
frame

a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5

In [169]:
frame.rank(axis=1)

a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0

In [ ]:
190