In [1]:
#将数组以二进制格式保存到磁盘

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
arr = np.arange(10)
np.save('some_array',arr)
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.savez('array_archive.npz',a=arr,b=arr)
arch = np.load('array_archive.npz')
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#存取文本文件

In [6]:
!type array_ex.txt #在Linux中将type改为cat
arr = np.loadtxt('array_ex.txt',delimiter=',')
arr

UnicodeEncodeError: 'ascii' codec can't encode character u'\u5728' in position 19: ordinal not in range(128)

In [7]:
#线性代数

In [9]:
x = np.array([[1.,2.,3.],[4.,5.,6.]])
y = np.array([[6.,23.],[-1,7],[8,9]])
x

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [10]:
y

array([[  6.,  23.],
       [ -1.,   7.],
       [  8.,   9.]])

In [11]:
x.dot(y)

array([[  28.,   64.],
       [  67.,  181.]])

In [12]:
np.dot(x,np.ones(3))

array([  6.,  15.])

In [15]:
from numpy.linalg import inv,qr
X = np.random.randn(5,5)
mat = X.T.dot(X)
inv(mat)

array([[  7.05219569, -14.19294614,  -3.63309195, -12.9030872 ,
          3.90644804],
       [-14.19294614,  40.12072892,   9.59410412,  35.32218123,
        -10.14789679],
       [ -3.63309195,   9.59410412,   2.49224925,   8.59427743,
         -2.50427197],
       [-12.9030872 ,  35.32218123,   8.59427743,  31.56476471,
         -9.25063776],
       [  3.90644804, -10.14789679,  -2.50427197,  -9.25063776,
          3.01462805]])

In [16]:
mat.dot(inv(mat))

array([[  1.00000000e+00,   0.00000000e+00,   1.66533454e-16,
         -1.11022302e-15,   5.55111512e-17],
       [  3.55271368e-15,   1.00000000e+00,   5.32907052e-15,
         -3.01980663e-14,   1.77635684e-15],
       [ -4.44089210e-16,   2.66453526e-15,   1.00000000e+00,
         -4.44089210e-15,   1.77635684e-15],
       [ -1.77635684e-15,  -1.06581410e-14,  -8.88178420e-15,
          1.00000000e+00,  -3.55271368e-15],
       [  0.00000000e+00,  -1.42108547e-14,  -3.55271368e-15,
          0.00000000e+00,   1.00000000e+00]])

In [18]:
q,r = qr(mat)
r

array([[-0.88338731,  1.22660856, -3.51049232, -0.79783078, -0.03207238],
       [ 0.        , -3.99294508, -3.96704777,  7.0138978 ,  4.92626503],
       [ 0.        ,  0.        , -5.32244097,  1.29068844, -0.55633442],
       [ 0.        ,  0.        ,  0.        , -0.76359172, -2.61385457],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.06754694]])

In [19]:
#随机数生成

In [20]:
samples = np.random.normal(size = (4,4))
samples

array([[ 0.65101788,  2.7068559 ,  1.26311027, -0.55927822],
       [-0.5362643 ,  0.33822084,  0.01844026,  0.79005859],
       [ 0.09135298, -0.42826918,  1.04853512,  3.1315665 ],
       [-1.09053583, -0.63180448,  0.0872605 ,  0.56480519]])

In [22]:
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0,1) for _ in xrange(N)]

1 loop, best of 3: 753 ms per loop


In [23]:
%timeit np.random.normal(size = N)

10 loops, best of 3: 35.9 ms per loop


In [29]:
import random 
import matplotlib.pyplot as plt
%matplotlib inline
position = 0
walk =[position]
steps = 1000
for i in xrange(steps):
    step = 1 if random.randint(0,1) else -1
    position += step
    walk.append(position)

In [30]:
nsteps = 1000
draws = np.random.randint(0,2,size=nsteps)
steps = np.where(draws >0,1,-1)
walk = steps.cumsum()
walk.min()

-31

In [31]:
walk.max()

23

In [32]:
(np.abs(walk) >= 10).argmax()

65

In [38]:
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0,2,size=(nwalks,nsteps))
steps = np.where(draws >0,1,-1)
walks = steps.cumsum(1)
walks

array([[-1,  0,  1, ..., 24, 23, 22],
       [ 1,  0,  1, ..., 26, 27, 28],
       [-1,  0,  1, ...,  8,  9, 10],
       ..., 
       [-1,  0, -1, ..., 26, 27, 28],
       [-1, -2, -3, ..., 54, 55, 56],
       [ 1,  2,  1, ...,  4,  3,  4]])

In [39]:
walks.max()

123

In [40]:
walks.min()

-125

In [41]:
hits30 = (np.abs(walks) >= 30).any(1)
hits30

array([ True,  True,  True, ...,  True,  True, False], dtype=bool)

In [42]:
hits30.sum()

3362

In [43]:
crossing_times = (np.abs(walks[hits30]) >=30).argmax(1)
crossing_times.mean()

505.79417013682331

In [44]:
steps = np.random.normal(loc=0,scale=0.25,
                        size=(nwalks,nsteps))