In [1]:
import pandas as pd
import numpy as np

In [2]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [3]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
arr2.ndim

2

In [5]:
arr2.shape

(2, 4)

In [6]:
arr1.dtype

dtype('float64')

In [7]:
arr2.dtype

dtype('int32')

In [8]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [9]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [10]:
np.empty((2,3,2))

array([[[  9.51892439e-299,  -3.89988594e-118],
        [ -1.16353052e-253,   7.57838527e-082],
        [  1.47267102e-212,  -9.04952577e-041]],

       [[ -2.70074618e-176,   1.75982120e-004],
        [  5.22043432e-140,  -2.09989712e+037],
        [ -6.26884422e-099,   4.08586339e+073]]])

In [11]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
arr1 = np.array([1,2,3],dtype=np.float64)
arr2 = np.array([1,2,3],dtype = np.int32)
arr1.dtype

dtype('float64')

In [13]:
arr2.dtype

dtype('int32')

In [14]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [15]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [16]:
arr = np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])
arr

array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [17]:
arr.astype(np.int32)
np.array([3,-1,-2,0,12,10],dtype=np.int32)
numeric_strings=np.array(['1.25','-9.6','42'],dtype=np.string_)
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

In [18]:
int_array = np.arange(10)
calibers = np.array([.22,.270,.357,.380,.44,.50],dtype=np.float64)
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [19]:
empty_uint32 = np.empty(8,dtype='u4')
empty_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

In [20]:
#数组和标量之间的运算

In [21]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [22]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [23]:
arr-arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [24]:
1 / arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [25]:
arr ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [26]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr[5]

5

In [29]:
arr[5:8]

array([5, 6, 7])

In [31]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [34]:
arr_slice = arr[5:8]
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [36]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [37]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [38]:
arr2d[0][2]

3

In [39]:
arr2d[0,2]

3

In [47]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [48]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [50]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [51]:
arr3d[1,0]

array([7, 8, 9])

In [52]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [54]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [58]:
arr2d[1,:2]

array([4, 5])

In [59]:
 arr2d[2,:1]

array([7])

In [60]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [61]:
arr2d[:2,1:] = 0

##布尔索引 

In [62]:
##布尔索引

In [71]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data = np.random.randn(7,4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='|S4')

In [72]:
data

array([[-1.00615731, -1.58158278,  1.23060883, -0.58905059],
       [-1.94564442,  0.80620468, -1.07284395,  0.1679754 ],
       [ 0.81676086,  0.86147353,  0.72025305,  1.70745149],
       [ 0.45379939,  0.81707131, -1.6568472 ,  0.44563001],
       [-0.02680055, -2.17584381,  0.67367986,  1.29192928],
       [ 0.19938467, -0.19301126, -0.01951646,  0.09692703],
       [-2.13522049, -0.50013951,  2.54271561, -0.36581399]])

In [73]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [74]:
data[names == 'Bob']

array([[-1.00615731, -1.58158278,  1.23060883, -0.58905059],
       [ 0.45379939,  0.81707131, -1.6568472 ,  0.44563001]])

In [75]:
data[names == 'Bob',2:]

array([[ 1.23060883, -0.58905059],
       [-1.6568472 ,  0.44563001]])

In [79]:
np.array([[-0.2349, 1.2792],
         [-0.0523, 0.0672]])
data[names == 'Bob',3]

array([-0.58905059,  0.44563001])

In [80]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [81]:
data[-(names == 'Bob')]

c:\python27\lib\site-packages\ipykernel\__main__.py:1: DeprecationWarning: numpy boolean negative, the `-` operator, is deprecated, use the `~` operator or the logical_not function instead.
  if __name__ == '__main__':


array([[-1.94564442,  0.80620468, -1.07284395,  0.1679754 ],
       [ 0.81676086,  0.86147353,  0.72025305,  1.70745149],
       [-0.02680055, -2.17584381,  0.67367986,  1.29192928],
       [ 0.19938467, -0.19301126, -0.01951646,  0.09692703],
       [-2.13522049, -0.50013951,  2.54271561, -0.36581399]])

In [82]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [83]:
data[mask]

array([[-1.00615731, -1.58158278,  1.23060883, -0.58905059],
       [ 0.81676086,  0.86147353,  0.72025305,  1.70745149],
       [ 0.45379939,  0.81707131, -1.6568472 ,  0.44563001],
       [-0.02680055, -2.17584381,  0.67367986,  1.29192928]])

In [84]:
data[data<0] = 0
data

array([[ 0.        ,  0.        ,  1.23060883,  0.        ],
       [ 0.        ,  0.80620468,  0.        ,  0.1679754 ],
       [ 0.81676086,  0.86147353,  0.72025305,  1.70745149],
       [ 0.45379939,  0.81707131,  0.        ,  0.44563001],
       [ 0.        ,  0.        ,  0.67367986,  1.29192928],
       [ 0.19938467,  0.        ,  0.        ,  0.09692703],
       [ 0.        ,  0.        ,  2.54271561,  0.        ]])

In [85]:
data[names != 'Joe'] = 7
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.        ,  0.80620468,  0.        ,  0.1679754 ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.19938467,  0.        ,  0.        ,  0.09692703],
       [ 0.        ,  0.        ,  2.54271561,  0.        ]])

In [86]:
arr = np.empty((8,4))
for i in range(8):
        arr[i] = i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [87]:
arr[[4,3,0,6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [88]:
arr[[-3,-5,-7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [89]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [91]:
arr[[1,5,7,2],[0,3,1,2]]
np.array([4,23,29,10])

array([ 4, 23, 29, 10])

In [94]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [95]:
arr[np.ix_([1,5,7,2],[0,3,1,2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

##数据转置和轴对称

In [96]:
##数据转置和轴对称

In [ ]:
110